### ISSUE TITLE
[Suggestion]: Explain how to add this mod as a dependency

### ISSUE THREAD

**Issue by saltyseadoggo** [Virtuoel/Statement#11]
### What is your suggestion?

Other library mods, such as [Economy for Fabric](https://www.curseforge.com/minecraft/mc-mods/fabric-economy) or [Meal API](https://github.com/FoundationGames/MealAPI) have written code blocks that show what to add to `build.gradle` to use the mod as a dependency. This mod has no such documentation, and, as such, I can't figure out how to add it as a dependency. I would appreciate documentation similar to those two mods on the Curseforge page and/or Github page that shows the code to add.

**Comment by Virtuoel** [comment]
Resolved now that README's been added.
