### ISSUE TITLE
[Bug]: Weird default states

### ISSUE THREAD

**Issue by Micalobia** [Virtuoel/Statement#13]
### Minecraft version(s)

1.18.1

### Mod loader

Fabric

### Mod loader version

0.12.6

### Fabric API version

0.44.1+1.18

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Forwarding this issue: https://github.com/Micalobia/Full-Slabs/issues/69

I suspect this issue is more Statement than my own mod, because when I updated to 1.18 I changed nothing about the code except what was absolutely necessary (bumping versions, changing the block entities to reflect 1.18 changes), and this seems to be that it's not applying the default state I said to [here](https://github.com/Micalobia/Full-Slabs/blob/Latest/src/main/java/dev/micalobia/full_slabs/FullSlabsMod.java#L61), instead opting for the X axis.

### Full list of installed mods

[All of Fabric 5](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5)

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Should hopefully now be resolved in 4.2.1. Do let me know if any issues still occur.

**Comment by Micalobia** [comment]
Seems to be working, thank you for the update!
