### ISSUE TITLE
[Bug]: Incompatibility with Dynmap for Fabric

### ISSUE THREAD

**Issue by Gryzle** [Virtuoel/Statement#15]
### Minecraft version(s)

1.18.1

### Minecraft version details

1.18.1

### Mod loader

Fabric

### Mod loader version

12.12

### Fabric API version

0.46.3

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

The blockstate changes causes an incompatibility with Dynmap.

### Full list of installed mods

Issue persists without any other non-required mods installed.

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Resolved on [Dynmap's end](https://github.com/webbukkit/dynmap/issues/3644).
