### ISSUE TITLE
[Bug]: Mixin Crash in 1.18.1 Dev Environment.

### ISSUE THREAD

**Issue by onyxromero** [Virtuoel/Statement#18]
### Minecraft version(s)

1.18.1

### Minecraft version details

1.18.1

### Mod loader

Forge

### Mod loader version

Forge 39.1.2

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Game Crashed in Dev Environment due to a Mixin failing to apply.

### Full list of installed mods

N/A, in a Dev Environment.

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [statement.mixins.json:compat116plus.StateManagerMixin] from phase [DEFAULT] in config [statement.mixins.json] FAILED during APPLY`

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: @Redirect annotation on fieldOfProxy could not find any targets matching 'method_30040' in net.minecraft.world.level.block.state.StateDefinition. Using refmap Statement-refmap.json [PREINJECT Applicator Phase -> statement.mixins.json:compat116plus.StateManagerMixin -> Prepare Injections ->  -> redirect$zzg000$fieldOfProxy(Lcom/mojang/serialization/Codec;Ljava/lang/String;Lcom/mojang/serialization/MapCodec;Ljava/util/function/Supplier;Ljava/lang/String;Lnet/minecraft/world/level/block/state/properties/Property;)Lcom/mojang/serialization/MapCodec; -> Parse`

**Comment by Virtuoel** [comment]
Should now be resolved with 4.2.2 release.
README has also been updated with more up to date info in the developer section about fixing mixin remapping.
