### ISSUE TITLE
[Bug]: Compatability Problem with Naturalist

### ISSUE THREAD

**Issue by Zarepheth** [Virtuoel/Statement#20]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19.2

### Mod loader

Fabric

### Mod loader version

fabric-loader-0.14.10-1.19.2

### Fabric API version

fabric-api-0.66.0+1.19.2.jar

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Crash to desktop at startup.

Due to the specifics of the error, it has already been reported on Naturalist, [Issue 26](https://github.com/starfish-studios/Naturalist/issues/26).

### Full list of installed mods

Copied from Crash Report:
		ad_astra: Ad Astra! 1.11.7
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalstructures: Additional Structures 4.1.0
		adorn: Adorn 3.7.0+1.19.2
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.17
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.2
		animatica: Animatica 0.5+1.19
		another_furniture: Another Furniture 2.1.2-1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		arcanus: Arcanus 1.30
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.3.56
		attributefix: AttributeFix 17.1.2
		attributetooltipfix: Attribute-Tooltip-Fix 1.0.0
		auto_third_person: Auto Third Person 1.2.1
		awesomeflooring: Awesome flooring 2.5.0
		axesareweapons: Axes Are Weapons 1.6.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		barteringstation: Bartering Station 4.0.3
		basicshields: Basic Shields [Fabric] 1.4.0-pre2-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		bclib: BCLib 2.1.4
		betteradvancements: Better Advancements 0.2.2.142
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterenchantmentboosting: Better Enchantment Boosting 1.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		bettersafebed: BetterSafeBed 4
		betterstats: Better Statistics Screen 2.0
			tcdcommons: TCD Commons API 1.0+1.19.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.8.1
		bettertridents: Better Tridents 4.0.1
		bettervillage: Better village 2.0.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		biomemakeover: Biome Makeover 1.19.2-1.6.0
		blockrunner: Block Runner 4.2.0
		blur: Blur (Fabric) 2.6.0
		boatiview: Boat Item View Fabric 0.0.4
		bolt: Bolt 1.2.1
			blue_endless_jankson: jankson 1.2.1
		bookshelf: Bookshelf 16.1.11
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.3-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botarium: Botarium 1.7.10
			team_reborn_energy: Energy 2.2.0
		bountiful: Bountiful 3.0.0
		buildguide: Build Guide 0.3.3
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carrier: Carrier 1.11.0
		cauldron_dyeing: Cauldron Dyeing 1.0.4
		chalk: Chalk 2.1.0+1.19
		chalk-colorful-addon: Chalk: Colorful-Addon 2.1.0+1.19
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		charmonium: Charmonium 4.2.1
		chat_heads: Chat Heads 0.7.1
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		chubbystuff: Chubby Stuff 2.0.1-fabric
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		clearview: Lava Clear View 5.0.0
		clickadv: Clickable Advancements Mod 2.9
		clickthrough: ClickThrough 1.19.1-fabric0.58.5-0.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 5.16
			fiber: fiber 0.23.0-2
		colorfulsubtitles: Colorful Subtitles 1.0.0
		colormatic: Colormatic 3.1.2+mc.1.19
		comforts: Comforts 6.0.3+1.19.2
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		craftingtweaks: Crafting Tweaks 15.1.0
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.9.1
		creaturesofthesnow: Creatures Of The Snow 3.1.0+1.19.2
		cryingghasts-fabric: Crying Ghasts (Fabric) 2.0
		cryingportals-fabric: Crying Portals (Fabric) 1.8
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		dankstorage: Dank Storage 1.19.2-4.3
		darkpaintings: DarkPaintings 13.1.2
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.8.0
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper and Darker 1.1.4
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 1.0.3
		deepslatecutting: Deepslate Cutting 1.5.0
		diagonalfences: Diagonal Fences 4.2.3
		dismountentity-fabric: Dismount Entity (Fabric) 2.1
		dragonloot: DragonLoot 1.1.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.3
		drippyloadingscreen: Drippy Loading Screen 1.6.5
		duckling: Duckling 2.0.7
		dungeons_arise: When Dungeons Arise 2.1.51
		dynamicfps: Dynamic FPS 2.2.0
		earthtojavamobs: Earth2Java 1.9.3
		easyanvils: Easy Anvils 4.0.6
		easymagic: Easy Magic 4.3.2
		ecologics: Ecologics 2.1.10
		edenring: EdenRing 0.6.4
		effective: Effective 1.4
		effecttooltips: EffectTooltips 5.0.1
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchantedshulkers: Enchanted Shulkers 1.0.4
		enchantinginfuser: Enchanting Infuser 4.2.2
		enchdesc: EnchantmentDescriptions 13.0.3
		endgoblintraders: End Goblin Traders 1.5.1
		enhancedgear: Enhanced Gear 1.3.0-1.19.2
		entity_texture_features: Entity Texture Features 4.2.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		environmentalcreepers: Environmental Creepers 1.6.0
		equipmentcompare: Equipment Compare 1.3.1
		everycomp: Every Compat 1.19.2-2.1.4
		expandeddelight: Expanded Delight 0.2.5
		expandedstorage: Expanded Storage 8.1.0-beta.1
			ellemes_container_lib: Ellemes' Container Library 2.1.0-alpha.12
		experiencebugfix: Experience Bug Fix 18
		explorify-fabric: Explorify 1.19-1.2.0
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.66.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.1+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.3+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.0+a1d87cb890
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.33+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.7+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.10+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.18+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.0+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.13+12bfe4ea90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.15+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.16+12bfe4ea90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.3+3e1ba48e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.4
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
		fabrishot: Fabrishot 1.9.1
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		fallingtree: FallingTree 3.10.0
		fancymenu: FancyMenu 2.12.9
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.3
		farsight: Farsight Mod 1.19-2.1
		ferritecore: FerriteCore 4.2.1
		foodeffecttooltips: Food Effect Tooltips 1.0.1-1.19.2
		forgeconfigapiport: Forge Config API Port 4.2.7
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendlyfire: FriendlyFire 14.0.1
		friendsandfoes: Friends&Foes 1.6.1
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		ftbbackups2: FTB Backups 2 1.0.17
		ftblibrary: FTB Library 1902.3.10-build.156
		ftbquests: FTB Quests 1902.4.3-build.140
		ftbteams: FTB Teams 1902.2.9-build.61
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		galosphere: Galosphere 1.19.2-1.2.0
		geckolib3: Geckolib 3.1.37
			com_eliotlash_mclib_mclib: mclib 20
		geodes: More Geodes 1.5.2
		glowstoneinc: Use Glowstone dust as Glow Ink Sac 1.19.2-2
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		goodall: Goodall 1.1.1
		graphutil: GraphUtil-Fabric 1.0.0-mc1.19
		graveyard: The Graveyard 2.3
		grindenchantments: Grind Enchantments 2.0.0+1.19.2
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		highlighter: Highlighter 1.1.4
		horizontal-glass-panes: Horizontal Glass Panes 1.0.1
		horseexpert: Horse Expert 4.0.0
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.11
		immersive_portals: Immersive Portals 2.2.5
			imm_ptl_core: Immersive Portals Core 2.2.5
			q_misc_util: QMiscUtil 2.2.5
		immersive_weathering: Immersive Weathering 1.19.2-1.2.4
		indium: Indium 1.0.9+mc1.19.2
		inmis: Inmis 2.7.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inmisaddon: InmisAddon 1.0.2
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.8.5
		iris: Iris 1.4.2
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemborders: Item Borders 1.1.6
		itemfilters: Item Filters 1902.2.9-build.46
		itemmodelfix: Item Model Fix 1.0.3+1.19
		itemphysic: ItemPhysic (Fabric) 1.6.6
		jade: Jade 8.6.2
		jadeaddons: Jade Addons 3.0.0
		jamlib: JamLib 0.5.0
		java: OpenJDK 64-Bit Server VM 17
		just_end_anchor: Just An End Anchor 1.0.2
		kambrik: Kambrik 4.0-1.19.2
		kiwi: Kiwi Lib 8.1.2
		kleeslabs: KleeSlabs 12.1.0
		kofitable: Kofi Table 1.0.4+1.19.x
		konkrete: Konkrete 1.5.3
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		languagereload: Language Reload 1.3.2
		lazydfu: LazyDFU 0.1.3
		leaves_us_in_peace: Leaves Us In Peace 1.0.10
		libipn: libIPN 1.0.6
		libraryferret: Library ferret 3.0.0
		lightingwand: Lighting Wand 5.0.0
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.10.2
		magnumtorch: Magnum Torch 4.2.0
		maptooltip: Map Tooltip 2.0.0
		mavapi: More Axolotl Variants API 1.0.0
		mavm: More Axolotl Variants Mod 1.2.0
		maxhealthfix: MaxHealthFix 8.0.1
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mixintrace: MixinTrace 1.1.1+1.17
		mob_catcher: Mob Catcher 1.2.14
		modmenu: Mod Menu 4.1.1
		moonlight: Moonlight 1.19.2-2.1.10
		more_babies: More Babies 1.0.0
		more_gems: More Gems 1.4.53
			pugh_tools: Pugh Tools 1.3.23
		moremcmeta: MoreMcmeta 1.19-3.0.5
		mousetweaks: Mouse Tweaks 2.22
		mvs: Vanilla Structure Mod 2.5.9
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		nbtcrafting: NBT Crafting 2.2.3+mc1.19
		nears: Nears 1.2.3
		netherdepthsupgrade: Nether Depths Upgrade 1.1.0
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		onsoulfire: On Soul Fire 1.19-2
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		overpoweredmending: OverpoweredMending 2.8.2
		owo: oωo 0.9.0+1.19
		oxidized: Oxidized 1.7.2
		paintings: Paintings++ 10.2.4.0
		paradise_lost: Paradise Lost 0.2.0-beta+1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.7.1
			moretags: More Tags 3.0.5
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		passiveshield-fabric: Passive Shield (Fabric) 2.7
		patchouli: Patchouli 1.19.2-77-FABRIC
		pathunderfencegates: Path Under Fence Gates 1.2.1
		paxi: Paxi 1.19.2-Fabric-3.0
		peculiarpieces: Peculiar Pieces 1.2.13+1.19.x
			playerabilitylib: Pal 1.6.0
		pickupnotifier: Pick Up Notifier 4.2.0
		polylib: PolyLib 1900.0.2-build.42
		polymorph: Polymorph 0.46.0+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		precise_armor: Precise Armor 1.0
		preciseblockplacing: PreciseBlockPlacing 2.0.0
		puzzle: Puzzle 1.4.0-1.19
			puzzle-base: Puzzle Base 1.4.0-1.19
			puzzle-gui: Puzzle GUI 1.4.0-1.19
			puzzle-models: Puzzle Models 1.4.0-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.19
		puzzleslib: Puzzles Lib 4.3.12
		radiantgear: Radiant Gear 2.0.0+1.19.2
		realisticsleep: Realistic Sleep 1.6.0
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		resourcefullib: Resourceful Lib 1.1.17
		rightclickharvest: Right Click Harvest 3.0.6
		romod: Fabric Reinforced Obsidian 1.19.2-1.2.2
		rottencreatures: Rotten Creatures 1.0.1
		roughly_enough_trades: Roughly Enough Trades 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.572
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.3
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		satin: Satin 1.9.0
		sdrp: Simple Discord Rich Presence 3.0.4-build.27+mc1.19.2
		seasons: Fabric Seasons 1.4-BETA+1.19
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smallernetherportals-fabric: Smaller Nether Portals (Fabric) 2.5
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sod: Sod 22.10.13
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.13+mc1.19.2-build.76
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.15
		spark: spark 1.9.45
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.2.2
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.9
		statement: Statement 4.2.4+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
			statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		stb: Sneak Through Berries 5.0.0
		storagecabinet: Storage Cabinet 1.5.4
		strawgolem: Straw Golem 2.0.0b2
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.22
		takesapillage: Takes a Pillage 1.0.4
		taxfreelevels: Tax Free Levels 1.3.3
		teenycoal: Teeny Coal 1.1.4-1.19.x
		terrablender: TerraBlender 2.0.1.130
		terrestria: Terrestria 5.0.6
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.2.0
			terraform-config-api-v1: Terraform Config API (v1) 4.2.0
			terraform-dirt-api-v1: Terraform Dirt API (v1) 4.2.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.2.0
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.2.0
			terraform-tree-api-v1: Terraform Tree API (v1) 4.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
			terrestria-client: Terrestria: Client 5.0.6
			terrestria-common: Terrestria: Common 5.0.6
			terrestria-worldgen: Terrestria: World Generation 5.0.6
		the_bumblezone: The Bumblezone - Fabric 6.4.4+1.19.2
			fake-player-api: Fake Player API 0.5.0
		third_person_maps: Third Person Maps 1.4.0
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		timetolive: Time To Live 0.4
		tipsmod: Tips 8.0.3
		toms_storage: Tom's Simple Storage Mod 1.4.3
		toolstats: ToolStats 12.0.2
		tooltipscroller: Tooltip Texts Scroller 1.0.0
		tpcrosshair: Third Person Crosshair 1.2.1
		tradingpost: Trading Post 4.2.0
		transparent: Transparent 5.1.2
		trinkets: Trinkets 3.4.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		twilightforest: The Twilight Forest 4.2.310
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 2.0.591+1.19.2
				porting_lib_base: Porting Lib Base 2.0.591+1.19.2
				porting_lib_entity: Porting Lib Entity 2.0.591+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.591+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.591+1.19.2
				porting_lib_models: Porting Lib Models 2.0.591+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.591+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.591+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.591+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.591+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.591+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.591+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.591+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.591+1.19.2
							porting_lib_constants: Porting Lib Constants 2.0.591+1.19.2
						porting_lib_common: Porting Lib Common 2.0.591+1.19.2
			serialization_hooks: Serialization Hooks 0.3.22
		universal_ores: Universal Ores 1.4.2
		upgradedshulkers: Upgraded Shulkers 1.1.3-1.19
			kyrptconfig: Kyrpt Config 1.5.0-1.19
			shulkerutils: shulkerutils 1.0.4-1.19
		vanilla-hammers: Vanilla Hammers 3.5.0-1.19.2
			magna: Magna 1.8.0-1.19.2
			static-content: Static Content 1.0.2-1.16.2
				staticdata: Static Data 1.1.2
		veinmining: Vein Mining 1.0.0-beta.5+1.19.2
		villagernames: Villager Names 4.0.8
		visiblebarriers: Visible Barriers 1.5.3+1.19.x
		visuality: Visuality 0.5.5
		visualworkbench: Visual Workbench 4.2.0
		voidtotem: Void Totem 2.1.0
		voidz: VoidZ 1.0.9
		walllanterns: Lanterns Belong on Walls 1.4.0-1.19
		wands: Building Wands 2.6.3_release
		wartdecay: Wart Decay 1.0.1
		whyamionfire: Why Am I on Fire? 1.2.0
		windchimes: Windchimes 1.2.1
		wmitaf: WMITAF 3.1.1
		wolfarmorcompat: Wolf Armor Compat 1.0.2-1.19.2
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
		woof: Woof 3.0.0-1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yigd: You're in Grave Danger 1.4.5
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zoomify: Zoomify 2.8.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

Crash Report: 
[crash-2022-11-25_14.51.53-client.txt](https://github.com/Virtuoel/Statement/files/10095109/crash-2022-11-25_14.51.53-client.txt)

**Comment by Virtuoel** [comment]
Naturalist just merged my PR to fix this compat issue, so this should be fixed whenever their next version is released.
