### ISSUE TITLE
[Bug]: 1.20.1 Fabric Version not actually updated for 1.20.1

### ISSUE THREAD

**Issue by Gamemassa** [Virtuoel/Statement#28]
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.21

### Fabric API version

0.86.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

The 1.20.1 Fabric version of Statement looks like it wasn't actually correctly updated because it gives me this error message:

![image](https://github.com/Virtuoel/Statement/assets/18667108/5f56212b-cf6b-4d69-b191-048b5413b7d6)

It looks like the mod is still only looking for up to 1.16.0

### Full list of installed mods and their version numbers

Doesn't appear to be a mod conflict, so mod list doesn't seem necessary at present.

### Did the problem cause the game to crash?

Yes. (paste crash report below)

**Comment by Virtuoel** [comment]
Statement contains multiple compatibility modules, so the one for older versions showing up like that in the error screen is normal.
Please post the full error window and the contents of your crashlog as well.

**Comment by Gamemassa** [comment]
Here's the full error message:

![image](https://github.com/Virtuoel/Statement/assets/18667108/003fd70d-7470-48dd-b46d-c8b3104c924e)

And I don't have an actual crash report (because the game wasn't able to launch in the first place), but here's the latest.log, if that helps:
https://gist.github.com/Gamemassa/2117784764202273f3be53a3271c274a

**Comment by Virtuoel** [comment]
Aha, that explains it. The actual issue you've run into is that the version of BCLib you have requires a newer version of Fabric API. Updating Fabric API should fix the problem.

**Comment by Gamemassa** [comment]
So Statement is conflicting with BCLib? Otherwise, why would Statement be showing up in that Error Report?

**Comment by Virtuoel** [comment]
No, it's unrelated. When there's mod loading errors, Fabric Loader will always show the other Statement module in the list, just to say, "this is something that isn't being loaded", even if it's not causing any issues.

**Comment by Gamemassa** [comment]
Oh, gotcha. Also, I already pinged the BCLib team about their mod because the changelog for the latest version of BCLib says it's compatible with Fabric API 0.86.0, but when I put it in my mods folder and try to launch the game, as you see in the error log above, BCLib still says it's not compatible with 0.86.0 despite what the changelog said.

**Comment by Virtuoel** [comment]
From what I can tell, the problem is specifically with 0.86.0, as that version had a bug that was fixed in 0.86.1 and newer if I remember correctly.
