### ISSUE TITLE
[Suggestion]: 1.20.2 port

### ISSUE THREAD

**Issue by zeresss** [Virtuoel/Statement#31]
### 1.20.2 port

Are there any plans for a 1.20.2 port? If yes, may I know when it will be released?

**Comment by sternschnaube** [comment]
I would love to use it too >>> Scaffolding Extension.
Any update on it? 😊

**Comment by Virtuoel** [comment]
Resolved as of the 4.2.9 release.

**Comment by sternschnaube** [comment]
Thanks 🥳🥳
