### ISSUE TITLE
[Bug]: Can't place top slabs with 1.20.4

### ISSUE THREAD

**Issue by Gamemassa** [Virtuoel/Statement#32]
### Minecraft version(s)

1.20.4

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.15.7

### Fabric API version

0.96.3

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I added Statement to my custom modpack because it's required for another mod (Lanterns Belong on Walls), and suddenly I was unable to place slabs in the top half of a block space.

### Full list of installed mods and their version numbers

N/A - I don't think this field is applicable in this case. I originally thought that something was conflicting with another mod in my modpack, Slabs Expanded (a mod that allows mixed top and bottom slabs in one block space), but after around 3 hours of debugging that, I thought I had isolated Statement as the conflict, but then I switched to a different instance and ran Statement alone, and discovered that **there was no conflict** and Statement is causing the issue on its own.

### Did the problem cause the game to crash?

No.

**Comment by Gamemassa** [comment]
@Virtuoel Hi, just wondering if this is being looked at, because it seems like a major issue.

**Comment by Virtuoel** [comment]
I am unable to reproduce this issue with Statement on its own. It looks like SlabsExpanded is, for some reason, using vanilla's missing property exceptions to detect if a slab is not being interacted with in its mixed double slab logic instead of just checking if the blockstate in question has a slab's type property. Definitely worth reporting to them, as using exceptions for control flow when there's a non-exception-related way to do the same thing is not a good practice to rely on.

**Comment by Gamemassa** [comment]
> I am unable to reproduce this issue with Statement on its own. It looks like SlabsExpanded is, for some reason, using vanilla's missing property exceptions to detect if a slab is not being interacted with in its mixed double slab logic instead of just checking if the blockstate in question has a slab's type property. Definitely worth reporting to them, as using exceptions for control flow when there's a non-exception-related way to do the same thing is not a good practice to rely on.

That's strange, because I _was_ able to reproduce this issue running Statement on its own. That said, I will still pass your advice along to the Slabs Expanded dev, because I'm sure they'd find it interesting and helpful.

**Comment by Virtuoel** [comment]
Hmm, that's odd. If it's possible, would you be able to provide a video or gif of the slab not placing correctly (with the F3 screen open)?

**Comment by Gamemassa** [comment]
Hmmm. I just tried to recreate it again to make a GIF and now Statement is working on its own. That's super weird.

**Comment by Gamemassa** [comment]
Also, I passed your comment along to the Slabs Expanded developer. Unfortunately, they don't have a GitHub link on their Curseforge/Modrinth pages, so I just put it in the comments section of their Curseforge page.
