### ISSUE TITLE
Mixin Crash

### ISSUE THREAD

**Issue by WenXin20** [Virtuoel/Statement#6]
`Minecraft v1.16.5`
`Forge v36.1.24`
`More Waterlogging v1.5`
`Statement v4.0.1` (Required for the above mod)

After installing I seem to be getting a mixin crash, although I'm unsure which other mod it is conflicting with. I also have FerriteCore installed, so maybe related to #5? 
If not, I also have Snow Real Magic installed, which I believe also mixins Snowy Dirt Blocks.
[Crash Report](https://gist.github.com/WenXin20/2c42016cb3040aabe18cc00fb9f2c3d5#file-latest-log-L327)

**Comment by Virtuoel** [comment]
Duplicate of #5
