### ISSUE TITLE
Mixin Conflict w/ Connectivity Preventing Server Detection

### ISSUE THREAD

**Issue by WenXin20** [Virtuoel/Statement#7]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Statement v4.0.2`
[`Connectivity v2.0`](https://www.curseforge.com/minecraft/mc-mods/connectivity)

After adding Statement to my modpack, I am not able to connect to my server. Upon checking the latest.log, it appears a mixin injection failed, possibly a conflict with the mod Connectivity.
[Latest.log](https://gist.github.com/WenXin20/79c6d23a98a54ebf1fbc21f74a62e6bc)

![2021-06-20_23 28 47](https://user-images.githubusercontent.com/12000593/122707564-dab44b00-d21f-11eb-943d-3734814676a3.png)

**Comment by Virtuoel** [comment]
A someaddon mod's `@Overwrite` mixin conflicting again. Why am I not surprised.
Anyways, workaround added in b7021e895e9ff9a802cd59a2286235e8c1b96d8c as to not crash on startup. 
Update to Statement 4.0.3 and it should now work.

**Comment by WenXin20** [comment]
Thanks!
