### ISSUE TITLE
Crash: Mod File "has mods that were not found".

### ISSUE THREAD

**Issue by Derpercoaster** [Virtuoel/Statement#8]
Title explains it all. I have no idea what this means or what to do to fix it. Here's the crash report:

[crash-2021-07-22_22.18.06-fml.txt](https://github.com/Virtuoel/Statement/files/6866392/crash-2021-07-22_22.18.06-fml.txt)

**Comment by Virtuoel** [comment]
You appear to have downloaded the `-sources-dev` jar, which isn't usable by players. Check the downloads again for the jar without `-sources-dev` in the name.

**Comment by Derpercoaster** [comment]
That is the only version available to be downloaded. I am trying to get the forge version.

**Comment by Virtuoel** [comment]
Can you try downloading it once again? It should be giving the proper version now.

**Comment by Derpercoaster** [comment]
It only says "source code" on them. Are any of them correct?

**Comment by Virtuoel** [comment]
Hmm, I'm not sure where you're looking at if they all say source code. There should be a non-source version available. Here's various links to the current Forge version:
https://www.curseforge.com/minecraft/mc-mods/statement/files/3398645
https://modrinth.com/mod/statement/version/1a4rvqDA

**Comment by Derpercoaster** [comment]
Ah, I was clocking on the download link at the bottom of the page instead of the one at the top. it does not say source code anymore.
