### ISSUE TITLE
[Bug]: crash on startup MC 1.16.5 using mod version 4.1.0(fabric)

### ISSUE THREAD

**Issue by SpinnyBoiii** [Virtuoel/Statement#9]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

Fabric Loader 11.6

### Fabric API version

fabric-api-0.37.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

crash on startup after updating statement library v4.0.3 to v4.1.0

### Full list of installed mods

ticktock-1.2.0.jar"
TooManyOrigins-1.16.5-0.1.3.jar"
tougherglass-1.0.3.jar"
Towelette-4.1.6+1.16.2.jar"
TRansliterationLib-1.0.4.jar"
unlimiteddragoneggs-1.1.1.jar"
villagerfix-2.0.2+1.16.5.jar"
villagersleashed-1.0.jar"
voicechat-fabric-1.16.5-1.8.13.jar"
wearable-backpacks-1.3.jar"
worldedit-mod-7.2.4.jar"
wthit-2.10.5-fabric.jar"
YungsApi-1.16.5-Fabric-6.jar"
adventurez-1.1.7.jar"
animal_feeding_trough-1.0.2.jar"
anycapes-1.0.3+1.16.jar"
appleskin-fabric-mc1.16.x-2.1.0.jar"
bclib-0.1.45.jar"
better-end-0.9.8.5-pre.jar"
bettersleepplus-2.4.0.jar"
BetterStrongholds-Fabric-1.16.5-1.1.jar"
biome-makeover-1.16.5-1.3.8.jar"
blast-1.5.2.jar"
BOMD-1.1.2-1.16.5.jar"
can-i-mine-this-block-1.0.2.jar"
Cardinal-Components-API-2.8.3.jar"
chunk-activator-2.1.0+mc1.16.1.jar"
cleancut-mc1.16-2.1-fabric.jar"
cloth-config-4.11.26-fabric.jar"
colonies-1.1.1.jar"
colorbricks-fabric-1.16.5-1.2.0.jar"
cookiecore-0.0.6.jar"
Couplings-1.5.0+1.16.jar"
Croptopia-1.16.4-5-FABRIC-1.4.0.jar"
customfov-fabric-1.3.1-1.16.5.jar"
darkness-mc116-1.6.58.jar"
easiervillagertrading-1.16.5-fabric0.30.0-1.5.4.jar"
enhanced_attack_indicator-1.0.1+1.16.jar"
enhancedcelestials-1.0.2.jar"
EntityCulling-Fabric-1.3.0.jar"
extraorigins-1.16.5-12.jar"
fabric-api-0.37.1+1.16.jar"
fabric-language-kotlin-1.6.1+kotlin.1.5.10.jar"
fairenchanting-1.2.0.jar"
fatxporbs-0.0.9+1.16.4.jar"
flytre_lib-0.2.11.jar"
forging-beyond-0.0.1-1.16.5.jar"
geckolib-fabric-1.16.5-3.0.40.jar"
gravestone-1.16.2-1.0.0-alpha.4.jar"
grind-enchantments-1.1.3+1.16.3.jar"
here-be-no-dragons-1.0.0.jar"
hollowlogs-1.1.0.jar"
horse-stats-vanilla-4.1.8.jar"
hudplus-1.0.jar"
i-am-very-smart-2.1.0+mc1.16.1.jar"
images-1.0.2+1.16.4.jar"
InstantLava_Fabric1.16.2-1.2.1.jar"
inventoryprofiles-fabric-1.16.2-0.4.2.jar"
item-model-fix-1.0.2+1.16.jar"
lambdynamiclights-fabric-1.3.4+1.16.jar"
leukocyte-0.1.3.jar"
lithium-fabric-mc1.16.5-0.6.6.jar"
map-atlases-1.2.5.jar"
moborigins-1.4.0.jar"
modmenu-1.16.10.jar"
Monster-of-the-ocean-depths-3.1-1.16.5.jar"
morebakedfoods-1.1.0.jar"
notenoughanimations-1.2.4.jar"
npc-variety-1.16.4-1.2.4.jar"
Origins-1.16.5-0.7.3.jar"
Origins-Classes-1.16.5-1.1.1.jar"
OverpoweredMending-Fabric-1.16.5-2.2.3.jar"
pal-portalcrafter-2.0.1.jar"
paradox-slabs-0.1.1.jar"
Pehkui-2.2.1+1.14.4-1.17.jar"
PetOwner-1.8.0-1.16.5+.jar"
pumice-0.0.2.jar"
queks_end-1.1.jar"
quiver-2.16.1.jar"
recipecache-0.1.0.jar"
repairable-tridents-1.0.0.jar"
replanter-1.16.X-1.1.0.jar"
RiptideFix-1.2.0.jar"
riverredux-0.1.6.jar"
RoughlyEnoughItems-5.12.248.jar"
sihywtcamc-1.3+1.16.5.jar"
Silky-Spawners-2.1.0+build.2-1.16.jar"
SkrewsBlockVariantsMod.jar"
slimefinder-1.0.0.jar"
slimeorigin-3.0.0-1.16.x.jar"
smootherbedrock-1.0.1.jar"
sneaknetherportals-1.1.jar"
sodium-fabric-mc1.16.3-0.1.0.jar"
Statement-4.1.0+1.14.4-1.17.1.jar"

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

![image](https://user-images.githubusercontent.com/49210394/126837265-4c61941e-7787-4027-8637-b7e79aae9936.png)

**Comment by Virtuoel** [comment]
Sigh. Of course I made a typo on that. Fix'll be out shortly.
